repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.2.0
    hooks:
      - id: stylua-github
        args: ["--syntax", "Lua54"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
    -   id: shellcheck
        # SC1090: Can't follow non-constant source. Use a directive to specify location.
        # SC1091: Not following: file not found.
        # SC1071: ShellCheck only supports sh/bash/dash/ksh scripts. Sorry!
        args: ["--exclude=SC1090,SC1091,SC1071"]
        files: '.zshrc'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
