repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.2.0
    hooks:
      - id: stylua-github
        args: ["--syntax", "Lua54"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
